/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type DestinationTransformer from '#transformers/destination_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Destination = InferData<DestinationTransformer>
  export namespace Destination {
    export type Variants = InferVariants<DestinationTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
